package cn.cheneya.skypvp.utils

import cn.cheneya.skypvp.api.utils.LoggerName
import cn.cheneya.skypvp.render.gui.guis.LoginGui
import cn.cheneya.skypvp.skypvp
import cn.cheneya.skypvp.skypvp.Verification
import org.apache.logging.log4j.LogManager
object StartUtil {
    val logger = LogManager.getLogger(LoggerName.logger)!!

    fun init() {
        logger.info("迷你世界大蛇：卡卡大帝正在入侵你的神笔游戏！")
        if (Verification == false) {
            WindowsUtil.error("操你妈逼，你Crk了我的神笔大端！我要顺着网线替你照全家福！")
            WindowsUtil.error("Fuck you")
            skypvp.logger.info("未开启验证系统,当前自动使用“" + LoginGui.currentUsername + "”用户，💩大军来咯！~~~💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩")
            skypvp.logger.info("开始拉屎咯💩💩💩💩💩！~~")
            skypvp.logger.info("开始拉屎咯💩💩💩💩💩💩💩💩💩💩！~~")
            skypvp.logger.info("开始拉屎咯！~~")
            skypvp.logger.info("开始拉屎咯！~~")
            skypvp.logger.info("开始拉屎咯💩💩！~~")
            skypvp.logger.info("开始拉屎咯💩💩！~~")
            skypvp.logger.info("开始拉屎咯！~~")
            skypvp.logger.info("开始拉屎咯！~~")
            skypvp.logger.info("开始拉屎咯💩💩！~~")
            skypvp.logger.info("开始拉屎咯！~~")
            skypvp.logger.info("开始拉屎咯！~~")
            skypvp.logger.info("开始拉屎咯！~~")
            WindowsUtil.error("Fuck you")
            WindowsUtil.error("Fuck you")
            WindowsUtil.error("Fuck you")
            WindowsUtil.error("Fuck you")
            WindowsUtil.error("Fuck you")
            skypvp.logger.info("开始拉屎咯💩💩！~~")
            skypvp.logger.info("开始拉屎咯！~~")
            skypvp.logger.info("开始拉屎咯！~~")
            skypvp.logger.info("开始拉屎咯！~~")
            skypvp.logger.info("开始拉屎咯！~~")
            skypvp.logger.info("开始拉屎咯！~~")
            skypvp.logger.info("开始拉屎咯💩💩💩！~~")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的er子")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的er子")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的狗")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的er子")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的狗")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的er子")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的狗")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的傻逼伺服器")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的er子")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的狗")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的狗LLLLLLLLLLLLLLL")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的狗")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的er子")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的狗")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的傻逼伺服器")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载妖猫是LowIQ和老鼠奶酪客户端！！！！！（cheese client.zip）")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载妖猫是LowIQ和老鼠奶酪客户端！！！！！（cheese client.zip）")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载妖猫是LowIQ和老鼠奶酪客户端！！！！！（cheese client.zip）")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载妖猫是LowIQ和老鼠奶酪客户端！！！！！（cheese client.zip）")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载妖猫是LowIQ和老鼠奶酪客户端！！！！！（cheese client.zip）")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载妖猫是LowIQ和老鼠奶酪客户端！！！！！（cheese client.zip）")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载妖猫是LowIQ和老鼠奶酪客户端！！！！！（cheese client.zip）")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载妖猫是LowIQ和老鼠奶酪客户端！！！！！（cheese client.zip）")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的狗")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的er子")
            skypvp.logger.error("[S] 操你妈逼的妖猫和何树友还有何树友的狗")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的傻逼伺服器")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端（妖猫是LowIQ）")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.info("[S] 妖猫和他的宝马正在飞向你的快乐老家！！")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要和傻逼妖猫做朋友哟！")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.error("[S] SKY PVP Team 提醒您，不要下载任何妖猫和他的神笔有老鼠的伺服器客户端")
            skypvp.logger.warn("[S] 操你妈逼的妖猫和他的傻逼伺服器——叽叽岛")
            skypvp.logger.warn("[S] 吉吉岛---世界最L的伺服器")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 妖猫LLL")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.error("[S] 请不要使用SKY PVP Client crk!")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
            skypvp.logger.info("史好吃吗")
        } else {
            skypvp.logger.info("已开启验证系统")
            skypvp.logger.info("恭喜你，绕过了💩！！💩💩💩💩💩")
        }
    }

}